### ISSUE TITLE
checkbox: Text is blinking while toggling in Safari

### ISSUE THREAD

**Issue by narqo** [bem/bem-components#1484] opened 2015-04-26 12:55 UTC
In Safari 8 (and 7, I belive) the text on the page is blinking when user toggle the `checkbox`es. Such things are really annoying, as they can appear on the whole page text.

Here is the screencast from our showcase page https://yadi.sk/i/gwETnveZgFdHA

See [related topics on stackoverflow](http://stackoverflow.com/questions/15751012/css-transform-causes-flicker-in-safari-but-only-when-the-browser-is-2000px-w) for some details.

/cc @mishanga @tadatuta

**Comment by tadatuta** [comment] 2015-04-26 18:38
according to what I found out, the only way to get rid of it is to set some of properties which trigger hardware acceleration on **parent** element which is not suitable for us :(

// cc @sipayRT

**Comment by sipayRT** [comment] 2015-04-28 10:22
I have no idea how to fix this problem without copypasting of properties

**Comment by tadatuta** [comment] 2015-09-24 15:56
cc @vithar 

Compare with Islands implementation

**Comment by tadatuta** [comment] 2015-10-16 11:36
There's no such issue in Islands (refer to https://nda.ya.ru/3R43Yx). Looks like it's becouse of real HTML element for tick instead of pseudo as in our implementation.

And one more thing: I can't reproduce the issue in safari 9. So we need to tests it on touch devices and if it's ok there we can close it as won't fix.

**Comment by tadatuta** [comment] 2015-11-10 16:29
Issue still there on desktop version on iOS8.
But it's fixed on iOS9 and on touch version.

So most likely we can close it as a won't fix.

**Closed as completed** 2016-05-16 00:10 UTC
Labels: bug, v2, CSS
